[package]
name        = "three_puzzle"
description = "3目並べ (flix_game_engine game)"
version     = "0.1.0"
flix        = "0.75.1"
authors     = ["you <you@example.com>"]

[dependencies]
"github:ababup1192/flix_game_engine" = { version = "0.33.5", security = "unrestricted" }
